# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/zynq/led_ip/da_rom_saw/da_rom_saw.xci
# IP: The module: 'da_rom_saw' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/zynq/led_ip/da_rom_saw/da_rom_saw_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'da_rom_saw'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/zynq/led_ip/da_rom_saw/da_rom_saw.xci
# IP: The module: 'da_rom_saw' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/zynq/led_ip/da_rom_saw/da_rom_saw_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'da_rom_saw'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
