# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/SUGARPIE/Desktop/waveform/an108_wave.cache/wt [current_project]
set_property parent.project_path C:/Users/SUGARPIE/Desktop/waveform/an108_wave.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/SUGARPIE/Desktop/waveform/repo [current_project]
update_ip_catalog
set_property ip_cache_permissions disable [current_project]
add_files C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/triangle512.coe
add_files C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/imports/waveform/wavecoe/triangle512.coe
add_files C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/imports/waveform/wavecoe/sin512.coe
add_files C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/imports/waveform/wavecoe/saw512.coe
add_files C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/imports/waveform/wavecoe/square512.coe
add_files C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/imports/waveform/wavecoe/osd.coe
add_files c:/Users/SUGARPIE/Desktop/waveform/wavecoe/osd.coe
read_verilog -library xil_defaultlib {
  C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/src/an108_adc.v
  C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/src/ax_debounce.v
  C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/src/video_define.v
  C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/src/draw_bg.v
  C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/src/draw_grid.v
  C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/src/draw_wav.v
  C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/imports/14_hdmi_char/hdmi_char.srcs/sources_1/src/osd_display.v
  C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/src/timing_gen_xy.v
  C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/src/wav_top.v
}
read_ip -quiet C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/rgb2dvi_0/rgb2dvi_0.xci
set_property used_in_implementation false [get_files -all c:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_clocks.xdc]

read_ip -quiet C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/video_pll/video_pll.xci
set_property used_in_implementation false [get_files -all c:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/video_pll/video_pll_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/video_pll/video_pll.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/video_pll/video_pll_late.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/video_pll/video_pll_ooc.xdc]

read_ip -quiet C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/dpram2048x8/dpram2048x8.xci
set_property used_in_implementation false [get_files -all c:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/dpram2048x8/dpram2048x8_ooc.xdc]

read_ip -quiet C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/adda_pll/adda_pll.xci
set_property used_in_implementation false [get_files -all c:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/adda_pll/adda_pll_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/adda_pll/adda_pll.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/adda_pll/adda_pll_late.xdc]
set_property used_in_implementation false [get_files -all c:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/adda_pll/adda_pll_ooc.xdc]

read_ip -quiet C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/da_rom_square/ip/da_rom_square/da_rom_square.xci
set_property used_in_implementation false [get_files -all c:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/da_rom_square/ip/da_rom_square/da_rom_square_ooc.xdc]

read_ip -quiet C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/osd_rom/ip/osd_rom/osd_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/osd_rom/ip/osd_rom/osd_rom_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/constrs_1/new/an108_hdmi.xdc
set_property used_in_implementation false [get_files C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/constrs_1/new/an108_hdmi.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
