# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/SUGARPIE/Desktop/waveform/.Xil/Vivado-2028-SUGARPIE/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg400-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/rgb2dvi_0
    C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/da_rom
    C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/video_pll
    C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/dpram2048x8
    C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/adda_pll
    C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/osd_rom/ip/osd_rom
  } {
      C:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/rgb2dvi_0
    C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/da_rom
    C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/video_pll
    C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/dpram2048x8
    C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/ip/adda_pll
    C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/osd_rom/ip/osd_rom
  } {
      C:/Users/SUGARPIE/Desktop/waveform/.Xil/Vivado-2028-SUGARPIE/realtime/rgb2dvi_0_stub.v
      C:/Users/SUGARPIE/Desktop/waveform/.Xil/Vivado-2028-SUGARPIE/realtime/da_rom_stub.v
      C:/Users/SUGARPIE/Desktop/waveform/.Xil/Vivado-2028-SUGARPIE/realtime/video_pll_stub.v
      C:/Users/SUGARPIE/Desktop/waveform/.Xil/Vivado-2028-SUGARPIE/realtime/dpram2048x8_stub.v
      C:/Users/SUGARPIE/Desktop/waveform/.Xil/Vivado-2028-SUGARPIE/realtime/adda_pll_stub.v
      C:/Users/SUGARPIE/Desktop/waveform/.Xil/Vivado-2028-SUGARPIE/realtime/osd_rom_stub.v
      C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/src/an108_adc.v
      C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/src/ax_debounce.v
      C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/src/video_define.v
      C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/src/draw_bg.v
      C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/src/draw_grid.v
      C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/src/draw_wav.v
      C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/imports/14_hdmi_char/hdmi_char.srcs/sources_1/src/osd_display.v
      C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/src/timing_gen_xy.v
      C:/Users/SUGARPIE/Desktop/waveform/an108_wave.srcs/sources_1/src/wav_top.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/SUGARPIE/Desktop/waveform/.Xil/Vivado-2028-SUGARPIE/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
